feat(nml.py): add default name to new segments
The schema does not require the `name` attribute in `Segment`. However,
the NEURON code generator seems to require it:

```
Exception: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.neuroml.model.Segment.getName()" is null
```