chore(loaders): fix type hinting for doc generation
otherwise sphinx fails with:

```
  File
  "/home/asinha/Documents/02_Code/00_mine/NeuroML/software/libNeuroML/neuroml/loaders.py",
  line 191, in <module>
      ) -> neuroml.nml.nml.NeuroMLDocument:
      AttributeError: module 'neuroml' has no attribute 'nml'

```

Not sure what the root cause is, but this tweak fixes it.